package: fontconfig

slices:
  bins:
    essential:
      - libc6_libs
      - libfontconfig1_libs
      - libfreetype6_libs
      - fontconfig-config_etc
    contents:
      /usr/bin/fc-cache:
      /usr/bin/fc-cat:
      /usr/bin/fc-conflist:
      /usr/bin/fc-list:
      /usr/bin/fc-match:
      /usr/bin/fc-pattern:
      /usr/bin/fc-query:
      /usr/bin/fc-scan:
      /usr/bin/fc-validate:
